### PR TITLE
Hi, I found more PPDs by UTAX which are MIT style licensed please pull them so others with UTAX machines have fun too

### PR DESCRIPTION
**Pull request by openfnord**
Taken from a file from the utax support pages:

TALinuxPackages_cCD-cLP_20140115.tar.gz
I removed the install script, the filter binary the script wanted
to install and the difference between a 64bit and a 32bit version
as PPDs are text files so there is no difference there.
The Global files vs EU files differ slightly for example
the default options for duplex printing.
The languages differ as the texts are in the local language
As you see from the PPDs Utax licensed the PPDs in MIT style.

Also note that UTAX and Triumph Adler are the same, just different names
for the same stuff. Some small printers like LP 3335 are rebranded
kyocera.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
I have checked your PPD files and encountered a problem with them.
```
$ grep -h cupsFilter db/source/PPD/Utax/*/*/*/*.ppd | sort | uniq
*cupsFilter: "application/vnd.cups-postscript 0 /usr/lib/cups/filter/kyofilter_B"
$
```
All the 996 PPDs (83 printer models * 2 regions * 6 languages) newly added by this PR have the `*cupsFilter:` line requiring the `kyofilter_B` CUPS filter. For me it looks like that these printers are not PostScript printers or at least the PPDs are only fully functional if the filter is available. And if the filter does irrelevant things meaning that the printers print as well without, the `*cupsFilter:` lines need to get removed from the PPDs as otherwise the PPDs simply do not work.

So to find out more about this, I would like to have a look into the original tarball from Utax. Can you make it available to me? Or post a download link for it? Thanks.

**Comment by openfnord** [comment]
Hi, I did not investigate the ppd files and I removed to binary blob, as thought,
that it is not needed, and one can do without it.
Also these printers understand pcl5 and postscript. They are oem versions of kyocera printers.

I own a copy monster Utax 350ci, where I contributed the ppd as I was searching again for it and found it having a MIT license.
As I bought the printer used, I first opened it, as I wanted to see the mainboard.
Also I did a backup of the EEPROMs to have a backup, for the case that I destroy proper operation using wrong settings in the service menue. One can adjust a lot of parameters there.
Inside the printer are many custom chips marked kyocera. So it can be seen that these machines are made by kyocera. Kyocera has an implementation of postscript they call kdpl as postscript is a trademark of Adobe.

So people owning these printers should try to operate the printer without the driver. For example I also owned a black and white TA laser called LP 35xx which is a kyocera printer, and worked perfectly with the ppd for the corrosponding kyocera model included in foomatic.

The original tar file I will send you in a second mail as I am writing this from my smartphone.

Regards,

Ludwig



On January 14, 2022 3:29:28 AM GMT+01:00, Till Kamppeter ***@***.***> wrote:
>I have checked your PPD files and encountered a problem with them.
>```
>$ grep -h cupsFilter db/source/PPD/Utax/*/*/*/*.ppd | sort | uniq
>*cupsFilter: "application/vnd.cups-postscript 0 /usr/lib/cups/filter/kyofilter_B"
>$
>```
>All the 996 PPDs (83 printer models * 2 regions * 6 languages) newly added by this PR have the `*cupsFilter:` line requiring the `kyofilter_B` CUPS filter. For me it looks like that these printers are not PostScript printers or at least the PPDs are only fully functional if the filter is available. And if the filter does irrelevant things meaning that the printers print as well without, the `*cupsFilter:` lines need to get removed from the PPDs as otherwise the PPDs simply do not work.
>
>So to find out more about this, I would like to have a look into the original tarball from Utax. Can you make it available to me? Or post a download link for it? Thanks.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenPrinting/foomatic-db/pull/25#issuecomment-1012693038
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by openfnord** [comment]
So again I was collecting PPDs by UTAX so people can enjoy their older UTAX printers using foomatic.
Also I moved the TA350ci, TA400ci, TA300ci PPDs according to the scheme most the orther PPDs were in,
and one set was missing the difference between EU and Global, so I copied them twice so they fit again.
Harddisk space is not that critical anymore.

So you might want to pull all but not the maybe_broken part.
The maybe_broken are from the following tarball:

From these drivers I removed the blob kyofilter_B and the install script. The 32bit and 64bit blobs differ.
https://www.utax.co.uk/wp-content/uploads/2021/05/TALinuxPackages_cCD-cLP_20140115.tar.gz
https://web.archive.org/web/20220117000635/https://www.utax.co.uk/wp-content/uploads/2021/05/TALinuxPackages_cCD-cLP_20140115.tar.gz

**Comment by tillkamppeter** [comment]
Thanks a lot, I am investigating the filter currently.

**Comment by openfnord** [comment]
Hi I found more PPDs from TriumphAdler (kyocera inside) they should be without fancy filters.
Please re-investigate so more people will have fun with TA office printers.

**Comment by tillkamppeter** [comment]
Do you have all PPDs you find up to now in this pull request? Or are there still some you have to add?

**Comment by openfnord** [comment]
Hi I think they are all, but I can search for more PPDs of other printers...

It would be nice if you would pull myTA PPDs now so others can enjoy all the PPDs for their Triumph Adler (Kyocera) printers.
If I find new PPDs it will take some time to organize them, then I will do a new pull request.

Thanks and all the best

luja


On March 20, 2022 2:08:01 PM GMT+01:00, Till Kamppeter ***@***.***> wrote:
>Do you have all PPDs you find up to now in this pull request? Or are there still some you have to add?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenPrinting/foomatic-db/pull/25#issuecomment-1073248241
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tillkamppeter** [comment]
Thank you very much.

I have merged this pull request now, so that the new Utax PPDs get available in the distributions and also in the PostScript Printer Application.

**Comment by openfnord** [comment]
Hi Till,

please make sure that the TA300ci, TA350ci, TA400ci are included.
In my first merge request I symlinked them as they support the same printer
engine (printers have different speed and component qualities e.g. duplex scanner
with two sensors instead of mechanically rotating pages, super sonic supervision
of paper draw). So please have a look at my ppd collection, the TA350ci, 300ci and 400ci
have different files by the vendor. So please work them in accordingly.

Thanks and best Regards

Ludwig

https://github.com/openfnord/PPDs/tree/main/Utax

https://github.com/openfnord/PPDs/tree/main/Utax/TA350ci/EU/English
(drivers for ta300ci, ta350ci, ta400ci)

https://github.com/openfnord/PPDs/tree/main/Utax/TA350ci/EU/English
On Sunday, March 27, 2022 22:01 CEST, Till Kamppeter ***@***.***> wrote:
 
 
Thank you very much.
I have merged this pull request now, so that the new Utax PPDs get available in the distributions and also in the PostScript Printer Application.

**Pull request merged**
