### PR TITLE
Added printers from OKI

### PR DESCRIPTION
**Pull request by tbertels**

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Thanks for the contribution.

1. First, all the files are under GPL license and so free software, this is required for us to accept them.
2. The second commit puts the PPD files into the root directory of the package, not into the subdirectory where PPDs for OKI belong into. See your first commit, there you did it correctly.
3. The first 3 files of the first commit use filters which are provided by OKI and possibly proprietary. Just donloading and using the PPD file will not make the printer work. One needs the filters which we do not have. The PPDX files in question are: `C330PS.ppd`, `OK400PCL.ppd`, and `OK400PS.ppd`.

To sole (2) please correct your second commit that the PPDs go into the correct directory and for (3) remove the files which need a proprietary filter from OKI.

**Comment by tillkamppeter** [comment]
You can re-add the files from (2), `OKB440_a.ppd` and `OKB430_a.ppd`, but add them into the directory `db/source/PPD/Oki/`. Thanks.

**Comment by tillkamppeter** [comment]
Thanks, this looks nice now.

Did you run the files through the `cupstestppd` utility to see whether they are correct? Could you do so?

**Comment by tbertels** [comment]
OKC321_a110.ppd doesn't conform:

find . -name \*.ppd \! -exec cupstestppd -q '{}' \; \  -exec cupstestppd -v '{}' \;
      **FAIL**  Missing option OKOptionTray in UIConstraints "*OKOptionTray 0 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKOptionTray 0 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKOptionTray 0".
      **FAIL**  Missing option OKOptionTray in UIConstraints "*InputSlot Lower *OKOptionTray 0".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize A6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize A6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Postcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Postcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize DoublePostcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize DoublePostcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Env9 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Env9".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Env10 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Env10".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvMonarch *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvMonarch".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvDL *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvDL".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvC5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvC5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvChou3 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvChou3".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvChou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvChou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvYou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvYou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Envelope4Rotated *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Envelope4Rotated".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 3x5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 3x5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 4x6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 4x6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 5x7 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 5x7".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType ULTRAHEAVY2 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType ULTRAHEAVY2".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType Labels1 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType Labels1".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType Labels2 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType Labels2".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion A6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion A6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Postcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Postcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion DoublePostcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion DoublePostcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Env9 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Env9".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Env10 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Env10".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvMonarch *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvMonarch".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvDL *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvDL".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvC5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvC5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvChou3 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvChou3".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvChou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvChou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvYou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvYou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Envelope4Rotated *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Envelope4Rotated".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 3x5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 3x5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 4x6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 4x6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 5x7 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 5x7".
./OKC321_a110.ppd:
    DETAILED CONFORMANCE TEST RESULTS
        PASS    DefaultImageableArea
        PASS    DefaultPaperDimension
        PASS    DefaultInstalledMemory
        PASS    DefaultDuplex
        PASS    DefaultInputSlot
        PASS    DefaultPageSize
        PASS    DefaultPageRegion
        PASS    DefaultTraySwitch
        PASS    DefaultOKResolution
        PASS    DefaultOKCollate
        PASS    DefaultOKEnvRotate
        PASS    DefaultOKMultiOutputMode
        PASS    DefaultOKOutputModeBlack
        PASS    DefaultOKImageSmoothing
        PASS    DefaultOKHairLine
        PASS    DefaultOKControl
        PASS    DefaultOKAlwaysPrnHT
        PASS    DefaultOKOverPrint
        PASS    DefaultOKScreenObo
        PASS    DefaultOKSeparationorder
        PASS    DefaultOKColorRenderStyle
        PASS    DefaultOKTargetColor
        PASS    DefaultOKBlackSubstitution
        PASS    DefaultOKPageSizeCheck
        PASS    DefaultOKMPTPageSizeCheck
        PASS    DefaultOKMediaType
        PASS    DefaultOKManualFeed
        PASS    FileVersion
        PASS    FormatVersion
        PASS    LanguageEncoding
        PASS    LanguageVersion
        PASS    Manufacturer
        PASS    ModelName
        PASS    NickName
        PASS    PageSize
        PASS    PageRegion
        PASS    PCFileName
        PASS    Product
        PASS    PSVersion
        PASS    ShortNickName
      **FAIL**  Missing option OKOptionTray in UIConstraints "*OKOptionTray 0 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKOptionTray 0 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKOptionTray 0".
      **FAIL**  Missing option OKOptionTray in UIConstraints "*InputSlot Lower *OKOptionTray 0".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize A6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize A6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Postcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Postcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize DoublePostcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize DoublePostcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Env9 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Env9".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Env10 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Env10".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvMonarch *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvMonarch".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvDL *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvDL".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvC5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvC5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvChou3 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvChou3".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvChou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvChou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize EnvYou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize EnvYou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize Envelope4Rotated *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize Envelope4Rotated".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 3x5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 3x5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 4x6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 4x6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageSize 5x7 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageSize 5x7".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType ULTRAHEAVY2 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType ULTRAHEAVY2".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType Labels1 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType Labels1".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*OKMediaType Labels2 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *OKMediaType Labels2".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion A6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion A6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Postcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Postcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion DoublePostcard *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion DoublePostcard".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Env9 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Env9".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Env10 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Env10".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvMonarch *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvMonarch".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvDL *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvDL".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvC5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvC5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvChou3 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvChou3".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvChou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvChou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion EnvYou4 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion EnvYou4".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion Envelope4Rotated *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion Envelope4Rotated".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 3x5 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 3x5".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 4x6 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 4x6".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*PageRegion 5x7 *InputSlot Lower".
      **FAIL**  Missing choice *InputSlot Lower in UIConstraints "*InputSlot Lower *PageRegion 5x7".
        WARN    Size "OKLegal" should be the Adobe standard name "8.5x13.5".
        WARN    Size "Envelope4Rotated" should be the Adobe standard name "Env215.9x297.04mm".
        WARN    Size "PRC16K184x260" should be the Adobe standard name "184x260mm".
        WARN    Size "PRC16K195x270" should be the Adobe standard name "195x270mm".
        WARN    Size "PRC16K197x273" should be "7,75x10,75".
        WARN    DefaultOKOptionTray has no corresponding options.
        WARN    DefaultOKOptionDuplex has no corresponding options.
    70 ERRORS FOUND

**Comment by tillkamppeter** [comment]
All `FAIL` messages are about the UIConstraints, combinations of settings which are not valid, mostly page sizes which cannot get delivered by the selected paper tray. The PPD should still work, probably OKI has put the same UIConstraints into all PPDs even if some printers do not have all the specified trays and sizes. The invalid UIContraints are simply ignored and printing will work independent of this.

**Comment by tbertels** [comment]
It makes sense, because I've printed successfully with it.

**Comment by tillkamppeter** [comment]
OK, probably the other PPDs from OKI which are already there gave the same FAILs on the constraints ...

Merging ...

Thanks a lot for your contribution!

**Comment by tbertels** [comment]
You're welcome, thank you too!

**Pull request merged**
