### PR TITLE
UTAX licenses its PPDs under a MIT license, which is nice of them. Un…

### PR DESCRIPTION
**Pull request by openfnord**
…fortunately the PPDs are not included in foomatic.

For the "old" TA350ci I needed the PPDs and saw that they may be shared, so I share them as they may be withdrawn by the manufacturer as the small copy monster is old and "end of life"

By the way ...
The Default Admin password for the TA350ci is 3500:
user: 3500
pass: 3500
The Service Menu can be entered from the main view using the code:
10871087
Here you can destroy everything:-) 
Helpful is printing colored registration pages for the printing unit which are to be scanned by the build-in scanner to optimize the printer color alignment.

### CODE REVIEW

**Comment by tillkamppeter** [comment]
After having merged this Pull Request I have also triggered a rebuild of the [PostScript Printer Application](https://snapcraft.io/ps-printer-app) in the Snap Store. So the Utax support is included there now, too.

**Comment by tillkamppeter** [comment]
Thanks a lot for your great contribution.

**Comment by paulmenzel** [comment]
@openfnord, could you please comment on where you downloaded these files from? Also you might archive the Web site in the [Wayback Machine](https://web.archive.org/).

**Comment by openfnord** [comment]
Hi, I downloaded thevfiles from utax.
Just do searches and you find them.
Also I added much of the urls to archive.org
So if a finding disappears please try at archive.org.

Have fun and if you need something, just drop me a mesage


chers

On October 31, 2022 11:52:24 AM GMT+01:00, Paul Menzel ***@***.***> wrote:
***@***.***, could you please comment on where you downloaded these files from? Also you might archive the Web site in the [Wayback Machine](https://web.archive.org/).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenPrinting/foomatic-db/pull/24#issuecomment-1296914781
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
"They who can give up essential liberty to obtain a little temporary
safety, deserve neither liberty nor safety." Benjamin Franklin (1775)

**Comment by paulmenzel** [comment]
Thank you for the quick response, and archiving the URLs. As you already know the URL, it’d be great, if you added one of them. (Thanks in advance.)

PS: When replying per email, please remove the quote/citation, as otherwise it’s shown in the GitHub comment.

**Comment by openfnord** [comment]
Hi all,

here are 2 links for example. I am sure that I used more sources for my collection:
"
https://github.com/openfnord/PPDs/blob/main/README.md:
...
For those folks who do not believe in me telling you that the PPDs of UTAX are MIT-licensed, please look here or ask your favorite search engine:
https://www.utax.co.uk/downloads/drivers/print-driver-linux-ppd-5057i/
https://web.archive.org/web/20220117001303/https://www.utax.co.uk/downloads/drivers/print-driver-linux-ppd-5057i/
"

Cheers,

luja

Am Montag, Oktober 31, 2022 12:20 CET, schrieb Paul Menzel ***@***.***>:
 
 
Thank you for the quick response, and archiving the URLs. As you already know the URL, it’d be great, if you added one of them. (Thanks in advance.)
PS: When replying per email, please remove the quote/citation, as otherwise it’s shown in the GitHub comment.

**Pull request merged**
