### PR TITLE
Added and modified printers from RICOH.​​

### PR DESCRIPTION
**Pull request by ZhangXiufu**

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Thanks for your new PPD files.

Unfortunately, in this pull request you messed up the ChangeLog file. It has > 40000 additions and > 40000 deletions. Probably every single line of it got modified, like for example by a change of encoding, replacing Unix-style line ends by DOS/Windows-style line ends, .... I cannot see what is wrong as GitHub's web interface is not able to display this huge change. Could you fix this? The change of the ChangeLog file should only be ~100 lines, mainly additions, not more.

Generally, before a `git commit`, please always do a `git diff` to see your changes and to see whether there apear only your changes and not a "white space change bomb" or anything other unexpected.

**Comment by ZhangXiufu** [comment]
Yes, there are 40137 lines in ChangeLog file.
Because we downloaded the current ChangeLog file from [https://raw.githubusercontent.com/ZhangXiufu/foomatic-db/master/ChangeLog](url) and then add the changes for this time. 
（this time's changelog please refer to '2021-05-24 JiangJunlan <Jiang.Junlan@cn.ricoh.com>'）
The history is from 2001-02-20 to 2021-05-24.
[ChangeLog.txt](https://github.com/OpenPrinting/foomatic-db/files/6550567/ChangeLog.txt)

If the change of the ChangeLog file should only have 100 lines, we want to confirm whether we only need to upload this time’s change log?

**Comment by tillkamppeter** [comment]
Thre is no hard limitation to 100 lines in ChangeLog, but ChangeLog contains entries for all changes which happened while the foomatic-db project existed. With each new change one entry gets added to ChangeLog and all the rest of the file stays untouched.  The diffstat should show the addition of the number of lines of the new entry and no removal of lines. In your case the diffstat shows the total number of lines of ChangeLog removed and the total number of lines of ChangeLog added. This means that each and every line of ChangeLog got changed, which is not correct.

So could you create a new pull request with the ChangeLog correctly edited (only your new entry changed, all already existing lines unchanged) and all PPD/XML file additions/changes as in this Pull Request? Thanks.

**Comment by ZhangXiufu** [comment]
We modified the ChangeLog file (7b02cb6), please merge them.
Thanks!

**Comment by tillkamppeter** [comment]
Done. Thank you very much.

**Comment by ZhangXiufu** [comment]
Thank you very much!
We checked the PPDs from site (http://www.openprinting.org/printers), but there are not these PPDs.
Could you please update the files to the site?

**Comment by tillkamppeter** [comment]
Sorry, forgot to update the server. I have done it now.

**Pull request merged**
